[package]
name = "choppedtuna/template"
description = "Game Template"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["node_modules"]

[dependencies]
Knit = "sleitnick/knit@^1"